apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-validate
  annotations:
    config.k8s.io/function: |
      container:
        image:  gcr.io/kpt-functions/gatekeeper-validate
        config.kubernetes.io/local-config: "true"
