apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: descheduler # {"$ref":"#/definitions/io.k8s.cli.setters.name"}
  app.kubernetes.io/managed-by: kpt
resources:
- resource/serviceaccount.yaml
- resource/clusterrole.yaml
- resource/clusterrolebinding.yaml
- resource/cronjob.yaml
- inventory-template.yaml
configMapGenerator:
- name: deschedulingpolicy
  files:
   - resource/deschedulingpolicy.yaml
